# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

dist: trusty

r:
#  - oldrel
  - release
  - devel

r_packages:
  - devtools

r_github_packages:
  - kenhanscombe/ukbtools

after_success:
  - Rscript -e 'covr::codecov()'